language: python
python:
- 2.7
install:
- python setup.py install
script:
- python setup.py test --verbose
deploy:
  provider: pypi
  user: netman92
  password:
    secure: Zz49O5xsm2Hj265csPtb/sdyKU5mnJW9eHfnjHkyWyhDcEHRZx2isOx8VCRB+vNDfseaRBRH8v10wuOOnUXzaIaqNpDsYQkCMmOCm65KQzgEIeI0+ga8tIfCaAAbrOn+sP6ZWuUIRw9mHEUcghZLIn58hJusKcB8GjCrZG0hWxw=
  server: https://testpypi.python.org/pypi
  on:
    tags: true
    repo: netman92/mobilem_cz
